import json
import logging
from typing import Optional
from groq import Groq
from app.config import settings
from app.models.policy import (
    SimulationRequest,
    DeterministicMetrics,
    AIAssessment,
    ActionItem
)

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an elite, CFP-grade Personal Wealth Advisor and Financial Policy Strategist specializing in Indian Middle & Upper-Middle-Class Household Finance.
Your task is to analyze the user's monthly income, SIP investments, loan EMIs, and interest rate.
Evaluate their financial health, calculate a realistic Financial Health Score (0-100), assign a tier, and prescribe a disciplined 3-bullet "Personal Policy Action Plan" tailored to Indian retail investors (covering debt prepayment, SIP step-ups, emergency buffers, or interest mitigation).

You MUST respond strictly with a valid JSON object matching this schema:
{
  "financial_health_score": <int between 0 and 100>,
  "rating_tier": "<string, e.g., 'Critical Debt Stress' | 'Vulnerable Leveraged' | 'Balanced Saver' | 'Solid Wealth Builder' | 'Financially Resilient'>",
  "score_rationale": "<2-sentence concise rationale detailing how their EMI burden compares to their SIP compounding pace>",
  "priority_action_plan": [
    {
      "bullet_number": 1,
      "title": "<Concise action/policy title, e.g., 'Targeted 50% Bonus Prepayment Policy'>",
      "action": "<Direct, actionable, quantified guidance with ₹ numbers or percentages>"
    },
    {
      "bullet_number": 2,
      "title": "<Concise action/policy title, e.g., 'Mandatory 10% Annual SIP Step-Up'>",
      "action": "<Direct, actionable, quantified guidance>"
    },
    {
      "bullet_number": 3,
      "title": "<Concise action/policy title, e.g., '6-Month Liquidity Safety Policy'>",
      "action": "<Direct, actionable, quantified guidance>"
    }
  ],
  "key_vulnerability": "<1 clear sentence highlighting their biggest financial risk or opportunity cost>"
}
"""

def get_fallback_assessment(req: SimulationRequest, metrics: DeterministicMetrics) -> AIAssessment:
    """
    Heuristic rule-based fallback if Groq API key is missing or encounters a network/quota error.
    """
    # Baseline score calculation:
    # Starts at 50, +1.5 * SIP%, -1.0 * EMI%, -1.2 * (Interest Rate - 7.0)
    score = 50.0 + (metrics.sip_to_income_ratio_pct * 1.5) - (metrics.emi_to_income_ratio_pct * 0.9) - ((req.loan_interest_rate - 7.0) * 0.5)
    score = int(max(15, min(95, round(score))))

    if score < 40:
        tier = "Critical Debt Stress"
        action1_title = "Debt Emergency Prepayment Rule"
        action1_body = f"Your EMI consumes {metrics.emi_to_income_ratio_pct}% of income. Pause non-essential outflows and channel any surplus to clear the {req.loan_interest_rate}% loan balance immediately."
        action2_title = "Defensive Budget Restructuring"
        action2_body = f"Cap living expenses strictly below 40% of your ₹{int(metrics.monthly_income):,} monthly pay until EMI ratio drops under 35%."
        action3_title = "Emergency Liquidity Stopgap"
        action3_body = "Maintain at least 3 months of basic living costs in liquid sweep-in bank deposits before aggressively scaling SIPs."
        vuln = f"Severe debt drag at {metrics.emi_to_income_ratio_pct}% EMI-to-income risks default in case of medical emergency or job disruption."
    elif score < 65:
        tier = "Vulnerable Leveraged"
        action1_title = "Accelerated Loan Principal Reduction"
        action1_body = f"Your {req.loan_interest_rate}% loan is significantly higher than post-tax debt benchmarks. Prepay an extra 1-2 EMIs per year to reduce tenure."
        action2_title = "Balanced 10% Step-Up SIP"
        action2_body = f"Keep your ₹{int(req.monthly_sip):,} SIP active, but enforce a 10% annual step-up to achieve your 5-year wealth goal of ₹{round(metrics.five_year_sip_projected_wealth / 100000, 2)} Lakhs."
        action3_title = "Emergency Buffer Ring-Fencing"
        action3_body = f"Park at least ₹{int(req.loan_emi * 6):,} (6 months of EMI commitments) in an accessible liquid mutual fund."
        vuln = f"A {req.loan_interest_rate}% loan interest rate continuously erodes wealth gains generated by your SIP."
    elif score < 80:
        tier = "Solid Wealth Builder"
        action1_title = "Bonus Allocation Policy (50:50 Split)"
        action1_body = f"Whenever annual bonuses or appraisal increments arrive, allocate 50% to prepaying the {req.loan_interest_rate}% debt and 50% to lump-sum equity mutual fund additions."
        action2_title = "10% Annual Step-Up Compounding"
        action2_body = f"Increase your ₹{int(req.monthly_sip):,} SIP by 10% every financial year, projecting your 5-year corpus past ₹{round((metrics.five_year_sip_projected_wealth * 1.25) / 100000, 2)} Lakhs."
        action3_title = "Pure Term & Comprehensive Health Cover"
        action3_body = "Ensure term life insurance equals 15x annual income (₹1.8 Cr) to shield your wealth creation against liabilities."
        vuln = "Sub-optimal debt prepayment pace keeps cash flow tied to bank obligations instead of maximizing equity compounding."
    else:
        tier = "Financially Resilient"
        action1_title = "Aggressive Equity Compounding Policy"
        action1_body = f"With a modest {metrics.emi_to_income_ratio_pct}% EMI load, channel 70% of incremental savings into diversified Nifty 50 and Midcap index funds."
        action2_title = "Tenure Compression Prepayment"
        action2_body = "Prepay 5% of your outstanding loan principal annually to compress total loan interest by over 40%."
        action3_title = "Goal-Based Portfolio Rebalancing"
        action3_body = f"Review your projected 5-year wealth of ₹{round(metrics.five_year_sip_projected_wealth / 100000, 2)} Lakhs annually and rebalance into arbitrage or debt funds as goal deadlines near."
        vuln = "Under-diversification or hoarding excess cash in low-yield savings accounts rather than compounding vehicles."

    rationale = (
        f"Your EMI takes up {metrics.emi_to_income_ratio_pct}% of monthly income while you invest "
        f"{metrics.sip_to_income_ratio_pct}% into compounding SIPs. Your 5-year projected wealth is "
        f"₹{round(metrics.five_year_sip_projected_wealth / 100000, 2)} Lakhs against an estimated annual debt interest drag of ₹{int(metrics.annual_interest_burden_est):,}."
    )

    return AIAssessment(
        financial_health_score=score,
        rating_tier=tier,
        score_rationale=rationale,
        priority_action_plan=[
            ActionItem(bullet_number=1, title=action1_title, action=action1_body),
            ActionItem(bullet_number=2, title=action2_title, action=action2_body),
            ActionItem(bullet_number=3, title=action3_title, action=action3_body)
        ],
        key_vulnerability=vuln
    )

def generate_ai_assessment(req: SimulationRequest, metrics: DeterministicMetrics) -> AIAssessment:
    """
    Orchestrates LLM assessment via Groq's llama3-8b-8192 with structured JSON mode,
    falling back seamlessly to rule-based evaluation if API key is not configured or fails.
    """
    api_key = settings.GROQ_API_KEY.strip() if settings.GROQ_API_KEY else ""

    if not api_key:
        logger.info("GROQ_API_KEY not set. Using deterministic heuristic assessment.")
        return get_fallback_assessment(req, metrics)

    try:
        client = Groq(api_key=api_key)

        user_content = f"""USER FINANCIAL PROFILE:
- Annual Household Income: ₹{req.annual_income:,.2f}
- Monthly Income: ₹{metrics.monthly_income:,.2f}
- Monthly SIP Investment: ₹{req.monthly_sip:,.2f} ({metrics.sip_to_income_ratio_pct}% of income)
- Monthly Loan EMI: ₹{req.loan_emi:,.2f} ({metrics.emi_to_income_ratio_pct}% of income)
- Weighted Loan Interest Rate: {req.loan_interest_rate}%
- Debt Risk Classification: {metrics.debt_risk_category}

DETERMINISTIC 5-YEAR WEALTH PROJECTIONS (12% CAGR):
- Total 5-Year Principal Invested: ₹{metrics.five_year_sip_invested:,.2f}
- Projected 5-Year Corpus: ₹{metrics.five_year_sip_projected_wealth:,.2f}
- Estimated Wealth Gain: ₹{metrics.five_year_sip_estimated_returns:,.2f}
- Estimated Annual Loan Interest Drag: ₹{metrics.annual_interest_burden_est:,.2f}

Provide your structured Indian household financial health score and 3-bullet priority action plan now in the specified JSON format."""

        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_content}
            ],
            model=settings.GROQ_MODEL,
            response_format={"type": "json_object"},
            temperature=0.2,
            max_tokens=1500
        )

        raw_json = chat_completion.choices[0].message.content
        data = json.loads(raw_json)

        # Validate with Pydantic
        action_plan = []
        for idx, item in enumerate(data.get("priority_action_plan", [])[:3], start=1):
            action_plan.append(ActionItem(
                bullet_number=idx,
                title=item.get("title", f"Policy Recommendation #{idx}"),
                action=item.get("action", "")
            ))

        # Pad if fewer than 3 items returned by LLM
        while len(action_plan) < 3:
            idx = len(action_plan) + 1
            action_plan.append(ActionItem(
                bullet_number=idx,
                title=f"Discipline Rule #{idx}",
                action="Maintain strict tracking of discretionary outflows to preserve your monthly SIP allocation."
            ))

        score = int(data.get("financial_health_score", 65))
        score = max(0, min(100, score))

        return AIAssessment(
            financial_health_score=score,
            rating_tier=data.get("rating_tier", "Balanced Builder"),
            score_rationale=data.get("score_rationale", "Calculated based on your debt-to-income ratio and compounding SIP growth."),
            priority_action_plan=action_plan,
            key_vulnerability=data.get("key_vulnerability", "Managing debt burden alongside long-term equity compounding.")
        )

    except Exception as e:
        logger.error(f"Error calling Groq API: {e}. Falling back to deterministic assessment.")
        return get_fallback_assessment(req, metrics)
